config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show] do
    member do
      patch :attend
      post :invite_to
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :user_events, foreign_key: :attended_event_id
  has_many :attendees, through: :user_events

  has_many :invites
  validates_associated :invites

  validates :date, presence: true
  validates :description, presence: true

  scope :upcoming_events, -> { where("date > ?", Date.today) }
  scope :previous_events, -> { where("date < ?", Date.today) }
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  belongs_to :events, class_name: 'Event', foreign_key: :event_id

  validates :sender_id, presence: true
  validates :recipient_id, presence: true
  validates :event_id, presence: true
  validates :recipient_id, uniqueness: { scope: :event_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_events, foreign_key: :attendee_id
  has_many :attended_events, through: :user_events
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id

  has_many :sent_invites, class_name: 'Invite', foreign_key: :sender_id
  has_many :received_invites, class_name: 'Invite', foreign_key: :recipient_id

  validates :username, presence: true
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :invited?
  before_action :attended?
  before_action :recipient_is_sender?
  skip_before_action :invited?, except: [:attend]
  skip_before_action :attended?, except: [:invite_to]
  skip_before_action :recipient_is_sender?, except: [:invite_to]

  def index
    @events = Event.all
    @upcoming_events = @events.upcoming_events.order(date: :asc)
    @previous_events = @events.previous_events.order(date: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    creator = User.find(session[:current_user]['id'])
    @event = creator.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path,
        notice: 'event successfully signed up.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors,
        status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.eager_load([:creator, :attendees]).find(params[:id])
    @invite = @event.invites.build
  end

  private

  def event_params
    params.require(:event).permit(:date, :description)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def destroy
    session.delete(:current_user)
    redirect_to events_path
  end

  def new
  end

  def create

    respond_to do |format|
      if @user_session = User.find_by(username: params[:session][:username])
        session[:current_user] = @user_session

        format.html { redirect_to root_path,
        notice: 'User successfully signed in.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors,
        status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user] = @user

        format.html { redirect_to root_path,
        notice: 'User successfully signed up.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors,
        status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def attend
    @event = Event.find(params[:id])

    begin
      if session[:current_user]
        attendee = User.find(session[:current_user]['id'])
        @event.attendees << attendee

        @invite = Invite.find_by_recipient_id(attendee.id)
        @invite.destroy 

        flash[:success] = 'You are now registered for this event.'
        redirect_to event_path(@event)
      else
        flash[:notice] = 'User is not signed in.'
        redirect_to root_path
      end
    rescue
      flash.now[:notice] = "You are already registered for this event."
    end
  end

  def invite_to
    @event = Event.find(invite_params[:event_id])
    @invite = @event.invites.build
    @recipient = User.find_by_username(invite_params[:username])

    @invite.sender_id = session[:current_user]['id']
    @invite.recipient_id = @recipient.id if @recipient.nil? == false

    if @invite.save
      flash[:success] = "You have invited #{@recipient.username} to the event."
      redirect_to event_path(@event)
    else
      render "events/show", :id => @event.id
    end
  end

  private

  def invite_params
    params.require(:invite).permit(:username, :event_id)
  end

  #check if user is already an attendee when inviting
  def attended?
    event = Event.where(id: "#{params[:id]}")[0]
    if event.attendees.find_by_username(invite_params[:username])
      flash[:notice] = "User is already an attendee."
      redirect_to event_path(event)
    end
  end

  #check if current user is inviting themselves
  def recipient_is_sender?
    event = Event.where(id: "#{params[:id]}")[0]
    user = User.where(username: "#{invite_params[:username]}")[0]
    if event.creator.id == user.id
      flash[:notice] = "You cannot invite yourself."
      redirect_to event_path(event)
    end
  end

  #check if user is already invited
  def invited?
    event = Event.where(id: "#{params[:id]}")[0]
    unless event.invites.find_by_recipient_id(session[:current_user]['id'])
      flash[:notice] = "You have not been invited to this event."
      redirect_to event_path(event)
    end
  end

end

app/views/events/_attend.html.erb
<%= form_for @event, url: attend_event_path,
    :html => { class: "attend-button-container" } do |f| %>
  <% f.button 'Attend Event', class: "attend-button" %>
<% end %>

app/views/events/_invite_to.html.erb
<% if notice.nil? == false %>
  <p class="notice"><%= notice %></p>
<% end %>

<% if @invite.errors.any? %>
  <ul>
  <% @invite.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @invite, :url => invite_to_event_path,
    :html => { class: "invite-form-container" } do |f| %>
    <%= f.hidden_field :event_id, :value => @invite.event_id %>
    <p>Invite a User to the Event</p>
    <%= f.label :username, 'Username:' %>
    <%= f.text_field :username %>
    <%= f.submit 'Invite User' %>
<% end %>

app/views/events/index.html.erb
<section id="top-bar" >
  <% if session[:current_user] %>
    <div class="left-button-container">
      <div class="current-user-container">
        <div class="current-user">Current User:</div>
        <div>
        <%= link_to session[:current_user]['username'],
        user_path(session[:current_user]['id']), class: "current-user-name" %>
        </div>
      </div>
      <%= link_to 'New Event', new_event_path, class: "top-buttons" %>
    </div>
    <div class="right-button-container">
      <%= link_to 'Sign Out', user_session_path(session), method: :delete,
      class: "top-buttons" %>
    </div>
  <% else %>
    <div class="left-button-container">
      <%= link_to 'Sign in', new_user_session_path, class: "top-buttons" %>
    </div>
    <div class="right-button-container">
      <%= link_to 'Sign up', new_user_path, class: "top-buttons" %>
    </div>
  <% end %>
</section>

<section id="events">
  <div class="event-list-container">
    <p class="list-category">Upcoming Events:</p>
    <div id="upcoming-events" class="event-container">
      <% if @upcoming_events.any? %>
        <% @upcoming_events.each do |event| %>
          <%= link_to event_path(event.id), class: "event-link" do %>
            <div class="user-event">
              <div>
                <%= "Event ##{event.id}" %>
              </div>
              <div>
                <%= event.date.strftime('%m/%d/%Y') %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <p>No Upcoming Events</p>
      <% end %>
    </div>
  </div>

  <div class="event-list-container">
    <p class="list-category">Previous Events:</p>
    <div id="previous-events" class="event-container">
      <% if @previous_events.any? %>
        <% @previous_events.each do |event| %>
          <div class="user-event">
            <%= link_to event_path(event.id), class: "event-link" do %>
              <div>
                <%= "Event ##{event.id}" %>
              </div>
              <div>
                <%= event.date.strftime('%m/%d/%Y') %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p>No Previous Events</p>
      <% end %>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <ul>
  <% @event.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @event, :html => { :class => "new-event" } do |f| %>
  <%= f.label :description, 'Event Description', class: "event-fields"%>
  <%= f.text_area :description, class: "event-description" %>
  <%= f.label :date, 'Event Date:', class: "event-fields" %>
  <%= f.date_field :date, as: :date,
  value: f.object.try(:strftime, "%m/%d/%Y"), class: "event-date" %>
  <%= f.submit 'Create Event', class: "submit-button" %>
<% end %>

<br>
<%= link_to '<<< Go Back', root_path, class: "go-back" %>

app/views/events/show.html.erb
<section id="event-go-back-container">
  <div class="main-event-container">
    <div class="show-event-container">
      <div class="user-name"><b><%= @event.creator.username %></b></div>
      <div class="event-text"><%= "Event ##{@event.id}" %></div>
      <div class="event-text">
        <%= "Event Date: #{@event.date.strftime('%m/%d/%Y')}" %>
      </div>
      <br>
      <div class="event-text">
        <b>Event Description:</b><br>
        <%= @event.description %>
      </div>
      <% if @event.attendees.any? %>
        <div class="attendees-container">
          <p class="list-category">Attendees:</p>
          <div class="attendee-list">
            <% @event.attendees.order(username: :asc).each do |attendee| %>
              <p class="attendee"><%= attendee.username %></p>
            <% end %>
          </div>
        </div>
      <% else %>
        <p>No Attendees</p>
      <% end %>

      <% if session[:current_user] && 
        @event.creator.id == session[:current_user]['id'] %>
        <%= render partial: 'invite_to' %>
      <% end %>

      <% if session[:current_user] &&
            @event.invites.find_by_recipient_id(session[:current_user]['id']) %>
        <%= render partial: 'attend' %>
      <% end %>
    </div>
  </div>
  <%= link_to '<<< Go Back', root_path, class: "go-back" %>
<section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<div class="new-user-container">
  <%= form_with scope: :session, url: user_sessions_path  do |f| %>
    <%= f.label :username, 'Username:', class: "form-label" %>
    <%= f.text_field :username, class: 'text-field' %>
    <%= f.submit 'Sign In', class: "submit-button" %>
  <% end %>
  <%= link_to '<<< Go Back', events_path, class: "go-back" %>
</div>

app/views/users/new.html.erb
<div class="new-user-container">
  <%= form_for @user, :html => { :class => "new-user" } do |f| %>
    <%= f.label :username, 'Create a new user', class: "form-label" %>
    <%= f.text_field :username, class: "text-field" %>
    <%= f.submit 'Create User', class: "submit-button" %>
  <% end %>
  <%= link_to '<<< Go Back', events_path, class: "go-back" %>
</div>

app/views/users/show.html.erb
<div class="user-name">
  <%= @user.username %>
</div>

<div class="event-list-container">
  <p class="event-category">Created Events:</p>
  <div id="created-events" class="event-container">
    <% if @user.created_events.any? %>
      <% @user.created_events.order(date: :asc).each do |event| %>
        <div class="user-event">
          <%= link_to "Event ##{event.id}", event_path(event.id), 
          class: "event-text" %>
          <div class="event-text"><%= event.date %></div>
        </div>
      <% end %>
    <% else %>
      <p>No created Events</p>
    <% end %>
  </div>
</div>

<div class="event-list-container">
  <p class="event-category">Upcoming Events:</p>
  <div id="upcoming-events" class="event-container">
    <% if @user.attended_events.upcoming_events.any? %>
      <% @user.attended_events.upcoming_events.order(date: :asc).each do |event| %>
        <div class="user-event">
          <%= link_to "Event ##{event.id}", event_path(event.id), 
          class: "event-text" %>
          <div class="event-text"><%= event.date %></div>
        </div>
      <% end %>
    <% else %>
      <p>No Upcoming Events</p>
    <% end %>
  </div>
</div>

<div class="event-list-container">
  <p class="event-category">Previous Events:</p>
  <div id="previous-events" class="event-container">
    <% if @user.attended_events.previous_events.any? %>
      <% @user.attended_events.previous_events.order(date: :desc).each do |event| %>
        <div class="user-event">
          <%= link_to "Event ##{event.id}", event_path(event.id), 
          class: "event-text" %>
          <div class="event-text"><%= event.date %></div>
        </div>
      <% end %>
    <% else %>
      <p>No Previously Attended Events</p>
    <% end %>
  </div>
</div>

<br>
<%= link_to '<<< Go Back', root_path, class: "go-back" %>